apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: task-manager
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/your-org/mini-task-manager.git'
    targetRevision: HEAD
    path: infrastructure/helm/task-manager
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: task-manager
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true